### ISSUE TITLE
Cannot compile dsputil.h:454:47: error: expected ',' or '...' before 'v1'

### ISSUE THREAD

**Issue by lpvm** [ponchio/untrunc#82]
Hi, 

I think I've installed everything needed as mentioned, but there's an error.

```
$ g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -I./libav-0.8.7 -L./libav-0.8.7/libavformat -lavformat -L./libav-0.8.7/libavcodec -lavcodec -L./libav-0.8.7/libavutil -lavutil -lpthread -lz
track.cpp:30:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS 1
 
In file included from /usr/include/c++/6.3/cstdint:41:0,
                 from /usr/include/c++/6.3/bits/char_traits.h:420,
                 from /usr/include/c++/6.3/string:40,
                 from track.h:25,
                 from track.cpp:21:
/usr/lib/gcc/x86_64-unknown-linux-gnu/6.3/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 
track.cpp:31:0: warning: "__STDC_CONSTANT_MACROS" redefined
 #define __STDC_CONSTANT_MACROS 1
 
In file included from /usr/include/c++/6.3/cstdint:41:0,
                 from /usr/include/c++/6.3/bits/char_traits.h:420,
                 from /usr/include/c++/6.3/string:40,
                 from track.h:25,
                 from track.cpp:21:
/usr/lib/gcc/x86_64-unknown-linux-gnu/6.3/include/stdint.h:7:0: note: this is the location of the previous definition
 #  define __STDC_CONSTANT_MACROS
 
In file included from ./libav-0.8.7/libavcodec/h264.h:32:0,
                 from track.cpp:46:
./libav-0.8.7/libavcodec/dsputil.h:454:47: error: expected ',' or '...' before 'v1'
     void (*butterflies_float)(float *restrict v1, float *restrict v2, int len);
                                               ^~
In file included from ./libav-0.8.7/libavcodec/h264.h:34:0,
                 from track.cpp:46:
./libav-0.8.7/libavcodec/mpegvideo.h:202:14: error: expected unqualified-id before 'class'
     AVClass *class;
              ^~~~~
./libav-0.8.7/libavcodec/mpegvideo.h:202:13: error: expected ';' at end of member declaration
     AVClass *class;
             ^
./libav-0.8.7/libavcodec/mpegvideo.h:202:19: error: expected identifier before ';' token
     AVClass *class;
                   ^
mp4.cpp:25:0: warning: "__STDC_LIMIT_MACROS" redefined
 #define __STDC_LIMIT_MACROS 1
 
In file included from /usr/include/c++/6.3/cstdint:41:0,
                 from /usr/include/c++/6.3/bits/char_traits.h:420,
                 from /usr/include/c++/6.3/string:40,
                 from mp4.cpp:22:
/usr/lib/gcc/x86_64-unknown-linux-gnu/6.3/include/stdint.h:5:0: note: this is the location of the previous definition
 #  define __STDC_LIMIT_MACROS
 
mp4.cpp:26:0: warning: "__STDC_CONSTANT_MACROS" redefined
 #define __STDC_CONSTANT_MACROS 1
 
In file included from /usr/include/c++/6.3/cstdint:41:0,
                 from /usr/include/c++/6.3/bits/char_traits.h:420,
                 from /usr/include/c++/6.3/string:40,
                 from mp4.cpp:22:
/usr/lib/gcc/x86_64-unknown-linux-gnu/6.3/include/stdint.h:7:0: note: this is the location of the previous definition
 #  define __STDC_CONSTANT_MACROS
```

**Comment by ponchio** [comment]
Ciao,
               I think it's a problem with the libav too old (for the
latest version.

I just updated to the latest ffmpeg version (just download the source
either from:

https://github.com/FFmpeg

or from

https://www.ffmpeg.org/download.html

And hopefully it should compile without too many problems....

Sorry,  it's a moving target...

Federico

**Comment by ponchio** [comment]
Ciao,
         I managed to make it work with the libav-12.2 and updated the
instructions, sorry for the mess.

Federico

**Comment by lpvm** [comment]
Hello Federico,

First of all, thank you for the tool (I haven't yet tried) and for the support.

The `ffmpeg` version I have installed is `3.3.4`, and it seems that it's the latest one.
Tried to compile as shown in the instructions, but got an error.  Did you use `ffmpeg` latest version or the ongoing development version?  Either way, I don't know if the problem is due to `ffmpeg`.

Please see attached log.  [log.txt](https://github.com/ponchio/untrunc/files/1375445/log.txt)

**Comment by ponchio** [comment]
Hi,
     I did used the libav-12.2 version (downloaded from the links in the
readme updated) .

The reason seems to be that ffmpeg uses the libswresample instead of
libavresample     by default or something along these lines.
If you want to use ffmpeg you could just use replace the lib in the .pro or
the commandline, there will be some other related lib required, I don't
remember exactly which,
but wasn't too difficult to fix.

It's much simpler to just use the libav-12.2 without ffmpeg. (
http://libav.org/download.html)

Federico

**Comment by lpvm** [comment]
Hi,

I just referred to `ffmpeg` because it could be the only difference between what you mention and what I did.  Do you mean I have to uninstall `ffmpeg` from my system?

Either way, I downloaded `libav` again, did the `make`, but when trying to compile `untrunc` it failed again with the same error it did as in the output I've shown in the last message.

**Comment by ponchio** [comment]
Hi,
       are you sure the compilation process points to the correct libav
libraries (and includes)?

You didn't include the command line in the log.txt, something that should
look something like this (for .cpp -> .o)

g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -D_FILE_OFFSET_BITS=64
-DVERBOSE -DVERBOSE1 -DQT_NO_DEBUG -I/usr/share/qt4/mkspecs/linux-g++-64
-I. -I/usr/include/qt4 -I../libav-12.2 -I. -o track.o track.cpp


And something like this for linking.

g++ -m64 -Wl,-O1 -o untrunc main.o atom.o mp4.o file.o track.o
-L/usr/lib/x86_64-linux-gnu ../libav-12.2/libavformat/libavformat.a
../libav-12.2/libavcodec/libavcodec.a ../libav-12.2/libavutil/libavutil.a
../libav-12.2/libavresample/libavresample.a -lz -lbz2 -lpthread

Federico

**Comment by ponchio** [comment]
Hi, sorry: the includes and linking paths can be inferred from the log and
I missed it, it looks ok.

Maybe it is juts missing the ../libav-12.2/libavresample/libavresample.a
and -lbz2 in the command line (old .pro?)

Federico

**Comment by lpvm** [comment]
Hi Federico,

Your first suggestion returns an error:
```

g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DVERBOSE -DVERBOSE1 -DQT_NO_DEBUG -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4 -I../libav-12.2 -I. -o track.o track.cpp

track.cpp:45:20: fatal error: config.h: No such file or directory
 #include <config.h>
                    ^
compilation terminated.
```

Regarding the second suggestion, I added `-lbz2` to the command line of the Readme, so it was:

`$ g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -I./libav-12.2 -L./libav-12.2/libavformat -lavformat -L./libav-12.2/libavcodec -lavcodec -L./libav-12.2/libavutil -lavutil -lpthread -lz -lbz2`

The proccess advanced a little but is now complaning about

```
In file included from mp4.cpp:30:0:
./libav-12.2/libavformat/avformat.h:712:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:382: undefined reference to `avresample_is_open'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_frame':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:221: undefined reference to `avresample_is_open'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_init_resample':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:163: undefined reference to `avresample_open'
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:169: undefined reference to `avresample_convert'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_frame':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:236: undefined reference to `avresample_convert'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_flush_resample':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:118: undefined reference to `avresample_convert'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_subpacket':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:414: undefined reference to `avresample_close'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_flush':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:616: undefined reference to `avresample_close'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_close':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:640: undefined reference to `avresample_free'
./libav-12.2/libavcodec/libavcodec.a(opusdec.o): In function `opus_decode_init':
/home/lupe/recolhidos/untrunc-master/libav-12.2/libavcodec/opusdec.c:704: undefined reference to `avresample_alloc_context'
collect2: error: ld returned 1 exit status
```

What to do next?  Please bear in mind that I don't know well the linking process.
Since this doesn't seem (to me) to be a problem outside of `untrunc` and `libav`, could you please download and start over as per the instructions on the Readme to see if the problems happen to you or not?

Thanks for your time,

Luis

**Comment by ponchio** [comment]
Hi,
  the first error is due to the fact that your path to libav-12.2 is
./libav-12.2 where in the command line it is ../libav-12.2....

In the second command line (which assumes your usual building process
manages to compiles track.cpp), it should be enough to add

-L./libav-12.2/libavresample -lavresample

Federico

**Comment by lpvm** [comment]
Hi Federico,

I managed to compile `untrunc` with the line:

`g++ -o untrunc file.cpp main.cpp track.cpp atom.cpp mp4.cpp -I./libav-12.2 -L./libav-12.2/libavformat -lavformat -L./libav-12.2/libavcodec -lavcodec -L./libav-12.2/libavutil -lavutil -L./libav-12.2/libavresample -lavresample -lpthread -lz -lbz2`

Thank you very much for your help.
