### ISSUE TITLE
Cannot compile on 16.04

### ISSUE THREAD

**Issue by michalskop** [ponchio/untrunc#130]
I followed the Installing instruction for Ubuntu, however I am getting:

`track.cpp:60:32: fatal error: libavcodec/h264dec.h: No such file or directory`

for the last command (`g++ ...`)

I was able to go through the "other operating systems" instructions.

**Comment by danboid** [comment]
Yep, same here under Ubuntu 18.04.

The Ubuntu build instructions don't work and should be removed to avoid others wasting their time trying them and and potentially thinking untrunc doesn't build.

**Comment by Hacklin** [comment]
You could try [this build script](https://github.com/ponchio/untrunc/pull/114).
See: `./build.sh --help` for help on its usage.

**Comment by ashishcompwiz** [comment]
did it work facing same issue here on ubuntu 16.04

**Comment by anthwlock** [comment]
@ashishcompwiz compilation is way simpler on this [fork](https://github.com/anthwlock/untrunc).
